name: Collect data

on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ipynotebooks/Forecasting_time_series/requirements.txt
      - name: Set API token
        run: echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV
      - name: Run the cron job script
        run: python ipynotebooks/Forecasting_time_series/cron_job.py
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
