name: Collect data

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  collect-data:
    runs-on: ubuntu-latest
    env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ipynotebooks/Forecasting_time_series/requirements.txt
      - name: Set API token
        run: echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV
      - name: Run the cron job script
        run: python ipynotebooks/Forecasting_time_series/cron_job.py
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "Update logs" || true
          git push      
